---
title: "The Energy Landscape"
author: "Fox Redmond"
date: "`r Sys.Date()`"
output: html_document
---

## Introduction

##### The feasibility of the switch to renewable energy sources is a heavy priority in the U.N.'s sustainable development goals (SDGs) 









## Narrative

#### (narrative here)



``` {r, echo=FALSE, include = FALSE}
library(readr)
library(gapminder)
library(dplyr)
library(ggplot2)
energy <- read_csv('../../data/IRENA data.csv', skip=1)
```

## Gapminder dataset

``` {r, echo=FALSE}
data(gapminder)
```

## Carbon emissions

``` {r, echo=FALSE}

url <- 'https://nyc3.digitaloceanspaces.com/owid-public/data/co2/owid-co2-data.csv'
carbon <-
  read_csv(url)
View(carbon)
carbon %>% pull(country) %>% unique
carbi <- 
  carbon %>% 
  filter(country %in% c('United States', 'China', 'India', 'Germany', 'Brazil', 'World')) %>% 
  mutate(population = population/1000000)

ggplot(carbi,
       aes(x = year,
            y = co2, 
           color = country)) +
  geom_point() +
  scale_y_continuous(trans = "log") +
  theme_bw() +
  labs(title = "working title",
       caption = "Annual co2 Emissions in 5 Countries and World",
       x = "Year",
       y = "Annual co2 Emissions (Million Metric Tons)")
```


``` {r, echo=FALSE}

ggplot(carbi, 
       aes(x = year,
           y = population,
           color = country)) +
  geom_point() +
  scale_y_continuous(trans = "log") +
  theme_bw() +
  labs(title = "working title",
       caption = "Change in population in 5 Countries and World",
       x = "Year",
       y = "Population (Millions)")
```

## Renewable Energy dataset


``` {r, echo=FALSE }
energy <- read_csv('../../data/IRENA data.csv', skip=1)
energy %>% names

energy %>% pull("Country/area") %>% unique

 energi <- 
  energy %>% 
  filter(`Country/area` %in% c('United States of America (the)', 'China', 'India', 'Germany', 'Brazil')) %>% 
  filter(`Technology` %in% c('Total renewable', 'Total non-renewable')) 


ggplot(energi, 
       aes(x = Year,
           y = as.numeric (`Electricity statistics`),
           color = `Country/area`)) +
  geom_point() +
  geom_path()+
  facet_wrap(~Technology) +
  theme_bw() +
  labs(title = "working title",
       caption = "x",
       x = "Year",
       y = "x")

```

## Levelized cost of energy

``` {r}
url <- 'https://raw.githubusercontent.com/ericmkeen/sewanee_esus/master/02_energy_sector/levelized-cost-of-energy.csv'
econ <- read_csv(url)
econ %>% head
View(econ)
econ %>% pull(country) %>% unique
```

```{r}

 econi <- 
  econ %>% 
  filter(country %in% c('United States)', 'China', 'India', 'Germany', 'Brazil')) %>% 
  filter(source %in% c('Solar photovoltaic', 'Onshore wind'))

ggplot(econi,
       aes(x = year,
           y = cost,
           color = source)) +
  geom_point() +
  theme_bw()+
  geom_hline(yintercept = 0.05, lty=2)+
  geom_hline(yintercept = 0.18, lty=2)+
  annotate(geom='text',
           x=1990, y=0.1, 
           label= 'Range of fossil\n fuel prices')
```


```{r}
library(knitr)
econ %>% 
  filter(year == 2020) %>% 
  group_by(source) %>% 
  summarize(cost = mean(cost, na.rm=TRUE)) %>% 
  kable
```

## Takeaways





## Data Sources



